import com.rhc.hadoop.model.Transaction;
import com.rhc.hadoop.drools.entry.Entry;

global com.rhc.hadoop.drools.entry.Collector collector;

rule "Map Transactions By Credit Card Number"
ruleflow-group "mapper-rules"
when
	transaction : Transaction(cc: creditCard, amount : amount)
then
	collector.collect(cc, "" + amount);
end

rule "Create Transactions"
ruleflow-group "mapper-rules"
when
	$entry : Entry()
then
	insert(new Transaction($entry.value));
end
